syntax = "proto2";

package com.andrerinas.openheadunit.aap.protocol.proto;
option java_outer_classname = "NavigationStatus";

enum MsgType {
    INSTRUMENT_CLUSTER_START = 0x8001;
    INSTRUMENT_CLUSTER_STOP = 0x8002;
    INSTRUMENT_CLUSTER_NAVIGATION_STATUS = 0x8003;
    NEXTTURNDETAILS = 0x8004;
    NEXTTURNDISTANCEANDTIME = 0x8005;
    INSTRUMENT_CLUSTER_NAVIGATION_STATE = 0x8006;
    INSTRUMENT_CLUSTER_NAVIGATION_CURRENT_POSITION = 0x8007;
}

message NavigationStatusStart
{
}

message NavigationStatusStop
{
}

message NavigationClusterStatus
{
    required NavigationStatusEnum status = 1;

    enum NavigationStatusEnum
    {
        UNAVAILABLE = 0;
        ACTIVE = 1;
        INACTIVE = 2;
        REROUTING = 3;
    }
}

message NextTurnDetail
{
    enum Side
    {
        LEFT = 0x01;
        RIGHT = 0x02;
        UNSPECIFIED = 0x03;
    }

    enum NextEvent
    {
        UNKNOWN = 0x00;
        DEPART = 0x01;
        NAME_CHANGE = 0x02;
        SLIGHT_TURN = 0x03;
        TURN = 0x04;
        SHARP_TURN = 0x05;
        U_TURN = 0x06;
        ON_RAMP = 0x07;
        OFFRAMP = 0x08;
        FORK = 0x09;
        MERGE = 0x0a;
        ROUNDABOUT_ENTER = 0x0b;
        ROUNDABOUT_EXIT = 0x0c;
        ROUNDABOUT_ENTER_AND_EXIT = 0x0d;
        STRAIGHT = 0x0e;
        FERRY_BOAT = 0x10;
        FERRY_TRAIN = 0x11;
DESTINATION = 0x12;
    }

    required string road = 1;
    optional Side side = 2;
    optional NextEvent next_turn = 3;
    optional bytes image = 4;
    optional int32 turn_number = 5;
    optional int32 turn_angle = 6;

}

message NextTurnDistanceEvent
{
optional int32 distance_meters = 1;
optional int32 time_to_turn_seconds = 2;
    optional int32 display_distance_e3 = 3;
    optional DistanceUnits display_distance_unit = 4;

    enum DistanceUnits
    {
        UNKNOWN_DISTANCE_UNIT = 0;
        METERS = 1;
        KILOMETERS = 2;
        KILOMETERS_P1 = 3;
        MILES = 4;
        MILES_P1 = 5;
        FEET = 6;
        YARDS = 7;
    }
}

message NavigationState
{
    repeated NavigationStep steps = 1;
    repeated NavigationDestination destinations = 2;
}

message NavigationStep
{
    optional NavigationManeuver maneuver = 1;
    optional NavigationRoad road = 2;
    repeated NavigationLane lanes = 3;
    optional NavigationCue cue = 4;
}

message NavigationManeuver
{
    optional NavigationType type = 1;

    enum NavigationType
    {
        UNKNOWN = 0;
        DEPART = 1;
        NAME_CHANGE = 2;
        KEEP_LEFT = 3;
        KEEP_RIGHT = 4;
        TURN_SLIGHT_LEFT = 5;
        TURN_SLIGHT_RIGHT = 6;
        TURN_NORMAL_LEFT = 7;
        TURN_NORMAL_RIGHT = 8;
        TURN_SHARP_LEFT = 9;
        TURN_SHARP_RIGHT = 10;
        U_TURN_LEFT = 11;
        U_TURN_RIGHT = 12;
        ON_RAMP_SLIGHT_LEFT = 13;
        ON_RAMP_SLIGHT_RIGHT = 14;
        ON_RAMP_NORMAL_LEFT = 15;
        ON_RAMP_NORMAL_RIGHT = 16;
        ON_RAMP_SHARP_LEFT = 17;
        ON_RAMP_SHARP_RIGHT = 18;
        ON_RAMP_U_TURN_LEFT = 19;
        ON_RAMP_U_TURN_RIGHT = 20;
        OFF_RAMP_SLIGHT_LEFT = 21;
        OFF_RAMP_SLIGHT_RIGHT = 22;
        OFF_RAMP_NORMAL_LEFT = 23;
        OFF_RAMP_NORMAL_RIGHT = 24;
        FORK_LEFT = 25;
        FORK_RIGHT = 26;
        MERGE_LEFT = 27;
        MERGE_RIGHT = 28;
        MERGE_SIDE_UNSPECIFIED = 29;
        ROUNDABOUT_ENTER = 30;
        ROUNDABOUT_EXIT = 31;
        ROUNDABOUT_ENTER_AND_EXIT_CW = 32;
        ROUNDABOUT_ENTER_AND_EXIT_CW_WITH_ANGLE = 33;
        ROUNDABOUT_ENTER_AND_EXIT_CCW = 34;
        ROUNDABOUT_ENTER_AND_EXIT_CCW_WITH_ANGLE = 35;
        STRAIGHT = 36;
        FERRY_BOAT = 37;
        FERRY_TRAIN = 38;
        DESTINATION = 39;
        DESTINATION_STRAIGHT = 40;
        DESTINATION_LEFT = 41;
        DESTINATION_RIGHT = 42;
    }

    optional int32 roundabout_exit_number = 2;
    optional int32 roundabout_exit_angle = 3;
}

message NavigationCue
{
    repeated string alternate_text = 1;
}

message NavigationLane
{
    repeated LaneDirection lane_directions = 1;

    message LaneDirection
    {
        optional Shape shape = 1;

        enum Shape
        {
            UNKNOWN = 0;
            STRAIGHT = 1;
            SLIGHT_LEFT = 2;
            SLIGHT_RIGHT = 3;
            NORMAL_LEFT = 4;
            NORMAL_RIGHT = 5;
            SHARP_LEFT = 6;
            SHARP_RIGHT = 7;
            U_TURN_LEFT = 8;
            U_TURN_RIGHT = 9;
        }

        optional bool is_highlighted = 2;
    }
}

message NavigationDestination
{
    optional string address = 1;
}

message NavigationCurrentPosition
{
    optional NavigationStepDistance step_distance = 1;
    repeated NavigationDestinationDistance destination_distances = 2;
    optional NavigationRoad current_road = 3;
}

message NavigationStepDistance
{
    optional NavigationDistance distance = 1;
    optional int64 time_to_step_seconds = 2;
}

message NavigationDestinationDistance
{
    optional NavigationDistance distance = 1;
    optional string estimated_time_at_arrival = 2;
    optional int64 time_to_arrival_seconds = 3;
}

message NavigationRoad
{
    optional string name = 1;
}

message NavigationDistance
{
    optional int32 meters = 1;
    optional string display_value = 2;
    optional DistanceUnits display_units = 3;

    enum DistanceUnits
    {
        UNKNOWN_DISTANCE_UNIT = 0;
        METERS = 1;
        KILOMETERS = 2;
        KILOMETERS_P1 = 3;
        MILES = 4;
        MILES_P1 = 5;
        FEET = 6;
        YARDS = 7;
    }
}