syntax = "proto2";

package com.andrerinas.openheadunit.aap.protocol.proto;
option java_outer_classname = "MediaPlayback";

enum MsgType {
    MSG_PLAYBACK_METADATA = 0x8001;
    MSG_PLAYBACK_STARTRESPONSE = 0x8002;
    MSG_PLAYBACK_METADATASTART = 0x8003;
}

message MediaPlaybackStatus
{
    enum State
    {
        STOPPED = 1;
        PLAYING = 2;
        PAUSED = 3;
    }

    optional State state = 1;
    optional string media_source = 2;
    optional uint32 playback_seconds = 3;
    optional bool shuffle = 4;
    optional bool repeat = 5;
    optional bool repeat_one = 6;
}

message MediaMetaData
{
    optional string song = 1;
    optional string artist = 2;
    optional string album = 3;
    optional bytes album_art = 4;
    optional string playlist = 5;
    optional uint32 duration_seconds = 6;
    optional int32 rating = 7;
}
