[versions]
agp = "9.3.0"
coreKtx = "1.19.0"
activity = "1.8.0"
annotation = "1.9.1"
junit = "4.13.2"
bouncycastle = "1.79"
jmdns = "3.6.3"
media3 = "1.11.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
bouncycastle = { group = "org.bouncycastle", name = "bcprov-jdk18on", version.ref = "bouncycastle" }
jmdns = { group = "org.jmdns", name = "jmdns", version.ref = "jmdns" }
androidx-media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3" }
androidx-media3-exoplayer-hls = { group = "androidx.media3", name = "media3-exoplayer-hls", version.ref = "media3" }
androidx-media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "media3" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
